// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PatientService.DataAccess.Concrete.EntityFramework;

#nullable disable

namespace PatientService.DataAccess.Migrations
{
    [DbContext(typeof(PatientAppointmentContext))]
    [Migration("20251217032302_seeddata-add")]
    partial class seeddataadd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Concrete.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("SlotId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("SlotId")
                        .IsUnique();

                    b.ToTable("Appointments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 12, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            PatientId = 1,
                            SlotId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 12, 11, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            PatientId = 2,
                            SlotId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 12, 12, 14, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            PatientId = 3,
                            SlotId = 8,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 12, 13, 16, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            PatientId = 4,
                            SlotId = 13,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Entities.Concrete.AppointmentSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("SlotDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId", "SlotDate", "StartTime", "EndTime")
                        .IsUnique();

                    b.ToTable("AppointmentSlots", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 12, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            EndTime = new TimeOnly(9, 30, 0),
                            SlotDate = new DateOnly(2025, 1, 15),
                            StartTime = new TimeOnly(9, 0, 0),
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 12, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            EndTime = new TimeOnly(10, 0, 0),
                            SlotDate = new DateOnly(2025, 1, 15),
                            StartTime = new TimeOnly(9, 30, 0),
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 12, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            EndTime = new TimeOnly(10, 30, 0),
                            SlotDate = new DateOnly(2025, 1, 15),
                            StartTime = new TimeOnly(10, 0, 0),
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 12, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            EndTime = new TimeOnly(11, 0, 0),
                            SlotDate = new DateOnly(2025, 1, 15),
                            StartTime = new TimeOnly(10, 30, 0),
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 12, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            EndTime = new TimeOnly(9, 30, 0),
                            SlotDate = new DateOnly(2025, 1, 15),
                            StartTime = new TimeOnly(9, 0, 0),
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 12, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            EndTime = new TimeOnly(10, 0, 0),
                            SlotDate = new DateOnly(2025, 1, 15),
                            StartTime = new TimeOnly(9, 30, 0),
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 12, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            EndTime = new TimeOnly(10, 30, 0),
                            SlotDate = new DateOnly(2025, 1, 15),
                            StartTime = new TimeOnly(10, 0, 0),
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 12, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            EndTime = new TimeOnly(14, 30, 0),
                            SlotDate = new DateOnly(2025, 1, 15),
                            StartTime = new TimeOnly(14, 0, 0),
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 12, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            EndTime = new TimeOnly(15, 0, 0),
                            SlotDate = new DateOnly(2025, 1, 15),
                            StartTime = new TimeOnly(14, 30, 0),
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 12, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            EndTime = new TimeOnly(15, 30, 0),
                            SlotDate = new DateOnly(2025, 1, 15),
                            StartTime = new TimeOnly(15, 0, 0),
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 12, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            EndTime = new TimeOnly(11, 30, 0),
                            SlotDate = new DateOnly(2025, 1, 15),
                            StartTime = new TimeOnly(11, 0, 0),
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 12, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            EndTime = new TimeOnly(12, 0, 0),
                            SlotDate = new DateOnly(2025, 1, 15),
                            StartTime = new TimeOnly(11, 30, 0),
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 12, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            EndTime = new TimeOnly(16, 30, 0),
                            SlotDate = new DateOnly(2025, 1, 15),
                            StartTime = new TimeOnly(16, 0, 0),
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 12, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            EndTime = new TimeOnly(17, 0, 0),
                            SlotDate = new DateOnly(2025, 1, 15),
                            StartTime = new TimeOnly(16, 30, 0),
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 12, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            EndTime = new TimeOnly(17, 30, 0),
                            SlotDate = new DateOnly(2025, 1, 15),
                            StartTime = new TimeOnly(17, 0, 0),
                            Status = 0
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdentityNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patient", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(1990, 5, 15),
                            CreatedAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Ahmet",
                            Gender = "Erkek",
                            IdentityNumber = "12345678901",
                            LastName = "Yılmaz",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1985, 8, 22),
                            CreatedAt = new DateTime(2024, 1, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Ayşe",
                            Gender = "Kadın",
                            IdentityNumber = "12345678902",
                            LastName = "Kaya",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(1978, 3, 10),
                            CreatedAt = new DateTime(2024, 1, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Mehmet",
                            Gender = "Erkek",
                            IdentityNumber = "12345678903",
                            LastName = "Demir",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateOnly(1995, 12, 1),
                            CreatedAt = new DateTime(2024, 1, 4, 14, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Fatma",
                            Gender = "Kadın",
                            IdentityNumber = "12345678904",
                            LastName = "Çelik",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateOnly(2000, 7, 25),
                            CreatedAt = new DateTime(2024, 1, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Ali",
                            Gender = "Erkek",
                            IdentityNumber = "12345678905",
                            LastName = "Öztürk",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("PatientService.Entities.Concrete.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorTitleId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorTitleId");

                    b.ToTable("Doctors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoctorTitleId = 1,
                            FirstName = "Kadir",
                            LastName = "Turan"
                        },
                        new
                        {
                            Id = 2,
                            DoctorTitleId = 2,
                            FirstName = "Haluk",
                            LastName = "Özdemir"
                        },
                        new
                        {
                            Id = 3,
                            DoctorTitleId = 3,
                            FirstName = "Neslihan",
                            LastName = "Doğan"
                        },
                        new
                        {
                            Id = 4,
                            DoctorTitleId = 4,
                            FirstName = "Emrullah",
                            LastName = "Yıldırım"
                        },
                        new
                        {
                            Id = 5,
                            DoctorTitleId = 5,
                            FirstName = "Mert",
                            LastName = "Gökçe"
                        });
                });

            modelBuilder.Entity("PatientService.Entities.Concrete.DoctorTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TitleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("DoctorTitles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TitleName = "Ortopedi"
                        },
                        new
                        {
                            Id = 2,
                            TitleName = "Dahiliye"
                        },
                        new
                        {
                            Id = 3,
                            TitleName = "Kulak Burun Boğaz"
                        },
                        new
                        {
                            Id = 4,
                            TitleName = "Noroloji"
                        },
                        new
                        {
                            Id = 5,
                            TitleName = "Diş"
                        });
                });

            modelBuilder.Entity("PatientService.Entities.Concrete.Waitlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NotifiedSlotId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PreferredDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("PreferredEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("PreferredStartTime")
                        .HasColumnType("time");

                    b.Property<int>("QueuePosition")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NotifiedSlotId");

                    b.HasIndex("DoctorId", "PreferredDate", "QueuePosition");

                    b.HasIndex("PatientId", "DoctorId", "PreferredDate", "Status");

                    b.ToTable("WaitlistEntries", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Appointment", b =>
                {
                    b.HasOne("PatientService.Entities.Concrete.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.AppointmentSlot", "AppointmentSlot")
                        .WithOne("Appointment")
                        .HasForeignKey("Entities.Concrete.Appointment", "SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppointmentSlot");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Entities.Concrete.AppointmentSlot", b =>
                {
                    b.HasOne("PatientService.Entities.Concrete.Doctor", "Doctor")
                        .WithMany("AppointmentSlots")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("PatientService.Entities.Concrete.Doctor", b =>
                {
                    b.HasOne("PatientService.Entities.Concrete.DoctorTitle", "DoctorTitle")
                        .WithMany("Doctors")
                        .HasForeignKey("DoctorTitleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DoctorTitle");
                });

            modelBuilder.Entity("PatientService.Entities.Concrete.Waitlist", b =>
                {
                    b.HasOne("Entities.Concrete.AppointmentSlot", "NotifiedSlot")
                        .WithMany()
                        .HasForeignKey("NotifiedSlotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Entities.Concrete.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotifiedSlot");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Entities.Concrete.AppointmentSlot", b =>
                {
                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Entities.Concrete.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("PatientService.Entities.Concrete.Doctor", b =>
                {
                    b.Navigation("AppointmentSlots");

                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("PatientService.Entities.Concrete.DoctorTitle", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
